### ISSUE TITLE
SMS sent, program not pulling 6 # code

### ISSUE THREAD

**Issue by Shmoly** [FuckingToasters/discord-phone-verifier#13] opened 2022-11-11 17:53 UTC
The program says the token is valid (I have checked for myself)
It buys a number from 5sim, solvs the captcha using capmonster (both work as expected)
"Successfully requested verification code" , I can see the verification code on 5sim but the program says "Discord haven't send the SMS so far 1/120 - 120/120

------------------------------------------------------------------------------------------------------------------------------------------
Exception in thread Thread-1 (verify):
Traceback (most recent call last):
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1016, in _bootstrap_inner
self.run()
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\threading.py", line 953, in run
self._target(*self._args, **self.kwargs)
File "C:\Users\killt\Desktop\GANG-Nuker PRODUCT\discord-phone-verifier-main\new version\main.py", line 221, in verify
VERIFYCODE = waitsms()
File "C:\Users\killt\Desktop\GANG-Nuker PRODUCT\discord-phone-verifier-main\new version\main.py", line 218, in waitsms
verify(totalthreads, threadindex, proxytype)
File "C:\Users\killt\Desktop\GANG-Nuker PRODUCT\discord-phone-verifier-main\new version\main.py", line 221, in verify
VERIFYCODE = waitsms()
File "C:\Users\killt\Desktop\GANG-Nuker PRODUCT\discord-phone-verifier-main\new version\main.py", line 217, in waitsms
elif str(PHONESERVICE).lower() == "fivesim": fivesim.deletenumber()
File "C:\Users\killt\Desktop\GANG-Nuker PRODUCT\discord-phone-verifier-main\new version\plugins\phoneservices\fivesim.py", line 29, in deletenumber
with requests.Client(headers=self.HEADERS) as client: response = client.get(url).json()
File "C:\Users\killt\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\httpx_models.py", line 743, in json
return jsonlib.loads(self.text, **kwargs)
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\json_init.py", line 346, in loads
return _default_decoder.decode(s)
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

![image](https://user-images.githubusercontent.com/39349500/201417117-a17c6ac4-619f-4fd9-97de-da748bf0aa2f.png)

------------------------------------------------------------------------------------------------------------------------------------------

Everything works as intended except the last part of fetching the SMS code and sending it back to discord.
 Thank you for your time.

Edit: Now it will say it sent a code but nothing gets received on 5sim.

**Comment by FuckingToasters** [comment] 2022-11-11 20:10
Hi, thank you for taking the time to write a detailed issue this help me a lot.
For some reason discord never sent a sms to my 5sim account so i can't really reproduce it thus you need to help me a bit.

Please edit plugins/phoneservices/fivesim.py on line 42 add print(response) and tell me what the actual response is when the sms appeard. 

thank you in advance

**Comment by Shmoly** [comment] 2022-11-11 20:29
![image](https://user-images.githubusercontent.com/39349500/201426309-e42bd00d-5040-4207-a7c0-2f07eaecf1a4.png)

Added "print(response)" on line 42 in @ plugins/phoneservices/fivesim.py as stated

**Comment by FuckingToasters** [comment] 2022-11-11 22:22
oh sry i mentioned the wrong line. put print(response) on line 46, this should print it on every check so also when the sms appeard, if the sms appeard pls send me the full response which should include the code

**Comment by Shmoly** [comment] 2022-11-12 02:53
Hi, i will post an update when I can. I am currently at work for the next 4 hours. I have sent a friend request over Discord as well to screenshare the issue if needed as well just so you can see exactly whats happening.

**Comment by Shmoly** [comment] 2022-11-12 08:38
![image](https://user-images.githubusercontent.com/39349500/201466208-d15ce938-38be-42ac-b8f1-179a192391be.png)
It says its verified but after refreshing, it is still not phone verified

**Comment by FuckingToasters** [comment] 2022-11-12 09:15
> ![image](https://user-images.githubusercontent.com/39349500/201466208-d15ce938-38be-42ac-b8f1-179a192391be.png) It says its verified but after refreshing, it is still not phone verified

i've updated the main.py with some print lines, if it found the verifycode it should print you 2 different lines with [DEBUGGING 1] and [DEBUGGING 2] before the actual response, you then can send me a screenshot of it.

**Comment by Shmoly** [comment] 2022-11-12 18:46
![image](https://user-images.githubusercontent.com/39349500/201489886-e8c794fc-f02a-4618-9e51-4899f35e823c.png)

The code is now instantly ending without getting a number or solving the captcha.

**Comment by FuckingToasters** [comment] 2022-11-13 13:24
> ![image](https://user-images.githubusercontent.com/39349500/201489886-e8c794fc-f02a-4618-9e51-4899f35e823c.png)
> 
> The code is now instantly ending without getting a number or solving the captcha.

The Issue is not from the Tool itself, the 5sim API to order numbers currently only have a `404 not found` text on the website and the actual API response status code is 302,

The number variable is defined with `None` at the top and then changed to the actual response later (if the status code is 200) but because the code isn't 200 the variable value won't be changed so it keep being None, then it post None in number field to discord so discord don't send captcha_key as response making the tool assume that no captcha is required.

It ofc. won't send a sms if it wasn't able to order the number.

**Comment by FuckingToasters** [comment] 2022-12-30 14:21
Issue was that discord detected the http requests. it's fixed in the dev branch at https://github.com/FuckingToasters/discord-phone-verifier/tree/dev

**Closed by FuckingToasters** 2022-12-30 14:21 UTC
